### ISSUE TITLE
Error with installing package from GitHub

### ISSUE THREAD

**Issue by dyyjenny** [jichunxie/CDI#11]
Hi, thanks for developing the package! I tried installing the package from GitHub via:

if (!requireNamespace("remotes", quietly = TRUE))                             
    install.packages("remotes")
remotes::install_github("jichunxie/CDI", build_vignettes = TRUE)

I ran into the error below when I tried installing on a R=4.1 server and locally (R=4.3), and ran into the error below:

── R CMD build ─────────────────────────────────────────────────
✔  checking DESCRIPTION meta-information ...
─  installing the package to process help pages
─  saving partial Rd database (29.8s)
E  creating vignettes (891ms)
   --- re-building ‘CDI.Rmd’ using rmarkdown
   Error: processing vignette 'CDI.Rmd' failed with diagnostics:
   there is no package called ‘BiocStyle’
   --- failed re-building ‘CDI.Rmd’

   SUMMARY: processing the following file failed:
     ‘CDI.Rmd’

   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'CDI' from GitHub:
  System command 'R' failed, exit status: 1, stdout & stderr were printed

Any insight on how to fix the issue? 

Thanks for your help!

**Comment by jichunxie** [comment]
Hi, the error message indicates that you might need to install the R package "BiocStyle" before installing CDI.
https://www.bioconductor.org/packages/release/bioc/html/BiocStyle.html

**Comment by dyyjenny** [comment]
Thank you so much for the timely help, that worked! Sorry I missed this part of the error printout.
