### ISSUE TITLE
Memory usage when dealing with large dataset

### ISSUE THREAD

**Issue by MarcusLCC** [jichunxie/CDI#8]
Hi, thank you for the development of this package.

I've been trying to calculate the CDI using `calculate_CDI` function, but since my dataset contains 460k cells, and even though I only subset the count matrix to the 3000 variable genes, the `calculate_CDI` process still takes up all the memory (at least 500Gb which then exceeds the memory limit of the server I use). The `seurat_obj` itself takes up around 30Gb memory.

Here is an example of my code

```
> seurat_obj
An object of class Seurat
55022 features across 463593 samples within 1 assays
Active assay: RNA (27307 features, 3000 variable features)

> var_genes <- VariableFeatures(seurat_obj)
> avail_res = c(0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.2, 1,4, 1.6, 1.8, 2, 3, 5)
> avail_res_names = paste0("resolution.", avail_res)
> cdi = calculate_CDI(sub_gcmat = extract_seurat(seurat_obj, "count", "counts")[var_genes,],
			cand_lab_df = extract_seurat(seurat_obj, "label", avail_res_names), 
			cell_size_factor = size_factor(extract_seurat(seurat_obj, "count", "counts")))

=>> PBS: job killed: mem 513799080kb exceeded limit 503316480kb
```

Could you please give some suggestions on how to avoid the memory issue and perform calculate_CDI on large scRNA-seq dataset? 

I appreciate a lot for your help.

Best regards,
Marcus

**Comment by jfanglovestats** [comment]
Hi Marcus,

Thanks for applying CDI and raising this question. 

The CDI value itself is summable across genes. One easy (may not be the best) solution is to divide the count matrix by genes and store them in separate files. For example, 100 genes for each file. Your 3,000 genes will end up in 30 files. Then you can calculate CDI for each file and sum the CDI values across files. 

The size factor calculation involves all selected genes and cells. In practice, the size factor is of limited impact to the final CDI values. For simplicity, you can set the size factor to be an all-1 vector (length = number of cells). If you want to calculate size factor accurately for this large dataset, please refer to my code in sessions "Write MM files" and "Size factor" of IPF/lung.R under [jfanglovestats/CDI_figures: Reproduce code](https://zenodo.org/record/7005019).

Hope this answers your question. 

Best,
Jiyuan
